[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'lifepillar/pgsql.vim'

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'sbdchd/neoformat'

[[plugins]]
repo = 'thinca/vim-quickrun'
